
#访问http://localhost:8761 进入管理界面
server:
  port: 8661

eureka:
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://peer2:8861/eureka/