
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#访问http://localhost:8765/hystrix.stream进入仪表盘监控界面
server:
  port: 8765

spring:
  application:
    name: service-feign

#开启feign自带断路器hystrix
feign:
  hystrix:
    enabled: true