
server:
  port: 8767
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ZeroOneSummer/springcloud_config/   #配置git仓库地址
          searchPaths: config     #配置仓库路径
          username:   #Git仓库为公开仓库，可以不填写用户名和密码
          password:
      label: master   #配置仓库的分支
