#端口
server:
  port: 8767

spring:
  application:
    name: config-server
  profiles:
    active: native   #默认git
  cloud:
    config:
#      label: master   #配置仓库的分支
      server:
#        git:
#          uri: https://github.com/ZeroOneSummer/springcloud_config/   #配置git仓库地址
#          searchPaths: classpath:/config    #配置本地仓库路径
#          username:   #Git仓库为公开仓库，可以不填写用户名和密码
#          password:
        native:   #本地存储config
          search-locations: file:F:/config  #如config-client-dev.properties在项目根目录则用classpath

bus:
  trace:
    enabled: true   #设置节点状态跟踪，也可以通过网页 http://localhost:8767/trace 可以看到相关发送事件的数据内容
  profiles:
    active: native


#注册到eureka服务
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

