
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#访问http://localhost:8764/hystrix.stream进入仪表盘监控界面
server:
  port: 8764

spring:
  application:
    name: service-ribbon